# Generated by Django 2.1.2 on 2018-11-16 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='post',
            name='date_start',
        ),
        migrations.RemoveField(
            model_name='post',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='post',
            name='roll',
        ),
    ]
