# Generated by Django 2.1.2 on 2018-11-16 17:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_auto_20181116_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_end',
            field=models.CharField(default=datetime.datetime(2018, 11, 16, 17, 35, 22, 952651, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='date_start',
            field=models.CharField(default=datetime.datetime(2018, 11, 16, 17, 35, 39, 247276, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='reason',
            field=models.CharField(default=datetime.datetime(2018, 11, 16, 17, 36, 6, 718249, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='roll',
            field=models.CharField(default=datetime.datetime(2018, 11, 16, 17, 36, 12, 417266, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
    ]
