# Generated by Django 2.1.2 on 2018-11-16 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_auto_20181116_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_end',
            new_name='leave_end_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date_start',
            new_name='leave_start_date',
        ),
    ]
