# Generated by Django 2.1.2 on 2018-12-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roombook', '0002_auto_20181202_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='no_of_rooms',
            field=models.IntegerField(),
        ),
    ]
