# Generated by Django 2.1.2 on 2018-12-03 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roombook', '0004_book_approve'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='reason',
            field=models.CharField(default='okay', max_length=500),
        ),
    ]
