# Generated by Django 2.1.2 on 2018-12-03 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roombook', '0005_book_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='vacant_date',
            field=models.DateField(default='2018-12-06', null=True),
        ),
    ]
