# Generated by Django 2.1.2 on 2018-12-03 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roombook', '0006_room_vacant_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(default='Pending', max_length=500),
        ),
        migrations.AlterField(
            model_name='room',
            name='vacant_date',
            field=models.DateField(default='2008-01-01', null=True),
        ),
    ]
